In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv(r"C:\Users\anjal\OneDrive\Desktop\marketing_campaign_messy.csv")

In [4]:
df.head(15)

,Campaign_ID,Campaign_Name,Channel,Region,Start_Date,Budget_USD,Leads_Generated,Conversions,ROI_Percent,Status
0,CMP-00001,Summer Sale,SOCIAL MEDIA,West,17/08/2022,TBD,712.0,30.0,57.78,inactive
1,CMP-00002,NaN,Organic,West,04-05-2023,$925,3462.0,NaN,NaN,NaN
2,CMP-00003,Summer Sale,NaN,north,2022/05/08,5664 USD,2962.0,71.0,194.99,active
3,CMP-00004,NaN,ppc,East,01-15-2023,$14230,4990.0,746.0,40.65,inactive
4,CMP-00005,Summer Sale,email,North,04-04-2024,26790.0,NaN,NaN,NaN,Completed
5,CMP-00006,NaN,organic,NORTH,2024/02/04,38742.0,1133.0,773.0,256.94%,completed
6,CMP-00007,black friday,EMAIL,NaN,06-26-2023,36756,938.0,NaN,NaN,completed
7,CMP-00008,Holiday Special,organic,East,2023-06-04,TBD,NaN,780.0,157.0,Active
8,CMP-00009,Summer Sale,Social Media,south,06-18-2024,16192 USD,NaN,835.0,293.18%,Completed
9,CMP-00010,New Year Promo,SOCIAL MEDIA,north,2024/06/12,14380.0,2553.0,NaN,125.81,active
10,CMP-00011,Summer Sale,EMAIL,north,24/08/2022,971,1875.0,NaN,11.97,NaN
11,CMP-00012,Summer Sale,EMAIL,NaN,2022/09/06,$27177,NaN,478.0,198.74,Active
12,CMP-00013,Black Friday,email,West,2022/07/14,9686.00,3789.0,453.0,20.0,Active
13,CMP-00014,Back to School,PPC,NaN,2023/05/13,14508,NaN,NaN,78.43,inactive
14,CMP-00015,Holiday Special,email,North,2023-08-17,49519,4785.0,161.0,287.84%,Inactive

In [5]:
df.dtypes

Campaign_ID            str
Campaign_Name          str
Channel                str
Region                 str
Start_Date             str
Budget_USD             str
Leads_Generated    float64
Conversions        float64
ROI_Percent            str
Status                 str
dtype: object

In [6]:
df.shape

(6000, 10)

In [7]:
# returns all unique (distinct) values in the 'Event' column
df['Channel'].unique()

<StringArray>
['SOCIAL MEDIA',      'Organic',            nan,          'ppc',
        'email',      'organic',        'EMAIL', 'Social Media',
          'PPC',        'Email']
Length: 10, dtype: str

In [8]:
df['Region'].unique()

<StringArray>
['West', 'north', 'East', 'North', 'NORTH', nan, 'south', 'South', 'East ']
Length: 9, dtype: str

In [9]:
df.info

<bound method DataFrame.info of      Campaign_ID   Campaign_Name       Channel Region  Start_Date Budget_USD  \
0      CMP-00001     Summer Sale  SOCIAL MEDIA   West  17/08/2022        TBD
1      CMP-00002             NaN       Organic   West  04-05-2023       $925
2      CMP-00003     Summer Sale           NaN  north  2022/05/08   5664 USD
3      CMP-00004             NaN           ppc   East  01-15-2023     $14230
4      CMP-00005     Summer Sale         email  North  04-04-2024    26790.0
...          ...             ...           ...    ...         ...        ...
5995   CMP-05996     SUMMER SALE  SOCIAL MEDIA   East  11-29-2022  23146 USD
5996   CMP-05997             NaN           ppc  north  05-26-2022    2362.00
5997   CMP-05998  Back to School           NaN  north  2022-06-13      21923
5998   CMP-05999     Summer Sale           ppc    NaN  05-07-2024   43082.00
5999   CMP-06000    black friday  Social Media  East   2023-10-08        TBD

      Leads_Generated  Conversions ROI_Percent     Status
0               712.0         30.0       57.78   inactive
1              3462.0          NaN         NaN        NaN
2              2962.0         71.0      194.99     active
3              4990.0        746.0       40.65   inactive
4                 NaN          NaN         NaN  Completed
...               ...          ...         ...        ...
5995           1260.0          NaN      292.71   inactive
5996            795.0        350.0         NaN     Active
5997              NaN          NaN         NaN        NaN
5998           1263.0          NaN         NaN        NaN
5999            110.0        795.0      59.11%        NaN

[6000 rows x 10 columns]>

In [10]:
df['Start_Date'].head(12)

0     17/08/2022
1     04-05-2023
2     2022/05/08
3     01-15-2023
4     04-04-2024
5     2024/02/04
6     06-26-2023
7     2023-06-04
8     06-18-2024
9     2024/06/12
10    24/08/2022
11    2022/09/06
Name: Start_Date, dtype: str

In [11]:
df.isnull().sum()

Campaign_ID          63
Campaign_Name      1231
Channel             587
Region             1240
Start_Date            0
Budget_USD         1260
Leads_Generated    2057
Conversions        2342
ROI_Percent        2031
Status             1186
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(0)

In [6]:
df['Budget_USD'].unique()

<StringArray>
[      'TBD',      '$925',  '5664 USD',    '$14230',   '26790.0',   '38742.0',
     '36756', '16192 USD',   '14380.0',       '971',
 ...
   '4507.00',     '35729',     '14423',     '46676',     '27069',   '30153.0',
 '23146 USD',   '2362.00',     '21923',  '43082.00']
Length: 4103, dtype: str

In [7]:
df['Status'].unique()

<StringArray>
[ 'inactive',         nan,    'active', 'Completed', 'completed',    'Active',
  'Inactive',    'ACTIVE',   'Pending']
Length: 9, dtype: str

In [8]:
#Data Cleaning



#Remove Extra Spaces
df = df.apply(
    lambda x: x.str.strip() if x.dtype == "object" else x
)

In [9]:
df = df.drop_duplicates()

print("Duplicates removed successfully")

Duplicates removed successfully

In [10]:
df.columns = df.columns.str.lower().str.strip().str.replace(" ", "_")

print(df.columns)

Index(['campaign_id', 'campaign_name', 'channel', 'region', 'start_date',
       'budget_usd', 'leads_generated', 'conversions', 'roi_percent',
       'status'],
      dtype='str')

In [11]:
# Fill missing values with mode

df['campaign_name'] = df['campaign_name'].fillna(df['campaign_name'].mode()[0])
df['channel'] = df['channel'].fillna(df['channel'].mode()[0])
df['status'] = df['status'].fillna(df['status'].mode()[0])

In [12]:
# Fill numerical missing values with median

df['leads_generated'] = df['leads_generated'].fillna(df['leads_generated'].median())
df['conversions'] = df['conversions'].fillna(df['conversions'].median())

In [13]:
# Convert region names into proper format

df['region'] = df['region'].str.strip().str.title()

print(df['region'].unique())

<StringArray>
['West', 'North', 'East', nan, 'South']
Length: 5, dtype: str

In [14]:
df.columns

Index(['campaign_id', 'campaign_name', 'channel', 'region', 'start_date',
       'budget_usd', 'leads_generated', 'conversions', 'roi_percent',
       'status'],
      dtype='str')

In [15]:
# Convert status into proper format

df['status'] = df['status'].str.strip().str.capitalize()

print(df['status'].unique())

<StringArray>
['Inactive', 'Completed', 'Active', 'Pending']
Length: 4, dtype: str

In [16]:
# Clean column names
df.columns = df.columns.str.lower().str.strip().str.replace(" ", "_")

print(df.columns)

Index(['campaign_id', 'campaign_name', 'channel', 'region', 'start_date',
       'budget_usd', 'leads_generated', 'conversions', 'roi_percent',
       'status'],
      dtype='str')

In [17]:
# Convert channel column into string
df['channel'] = df['channel'].astype(str)

# Remove extra spaces
df['channel'] = df['channel'].str.strip()

# Convert into proper format
df['channel'] = df['channel'].str.title()

# Replace invalid values with NaN
df['channel'] = df['channel'].replace(['Nan', 'Unknown', ''], np.nan)

# Fill missing values using mode
df['channel'] = df['channel'].fillna(df['channel'].mode()[0])

# Check final output
print(df['channel'].unique())

<StringArray>
['Social Media', 'Organic', 'Email', 'Ppc']
Length: 4, dtype: str

In [18]:
# Convert campaign_name column into string
df['campaign_name'] = df['campaign_name'].astype(str)

# Remove extra spaces
df['campaign_name'] = df['campaign_name'].str.strip()

# Convert into proper format
df['campaign_name'] = df['campaign_name'].str.title()

# Replace invalid values with NaN
df['campaign_name'] = df['campaign_name'].replace(
    ['Nan', 'Unknown', ''], 
    np.nan
)

# Fill missing values using mode
df['campaign_name'] = df['campaign_name'].fillna(
    df['campaign_name'].mode()[0]
)

# Check final output
print(df['campaign_name'].unique())

<StringArray>
[    'Summer Sale',    'Summer  Sale',    'Black Friday', 'Holiday Special',
  'New Year Promo',  'Back To School']
Length: 6, dtype: str

In [19]:
df.head()

,campaign_id,campaign_name,channel,region,start_date,budget_usd,leads_generated,conversions,roi_percent,status
0,CMP-00001,Summer Sale,Social Media,West,17/08/2022,TBD,712.0,30.0,57.78,Inactive
1,CMP-00002,Summer Sale,Organic,West,04-05-2023,$925,3462.0,489.0,NaN,Completed
2,CMP-00003,Summer Sale,Email,North,2022/05/08,5664 USD,2962.0,71.0,194.99,Active
3,CMP-00004,Summer Sale,Ppc,East,01-15-2023,$14230,4990.0,746.0,40.65,Inactive
4,CMP-00005,Summer Sale,Email,North,04-04-2024,26790.0,2449.0,489.0,NaN,Completed

In [20]:
df['start_date'] = pd.to_datetime(
    df['start_date'],
    format='mixed',
    errors='coerce'
)

In [21]:
print(df['start_date'].head())

0   2022-08-17
1   2023-04-05
2   2022-05-08
3   2023-01-15
4   2024-04-04
Name: start_date, dtype: datetime64[us]

In [22]:
df.head(50)

,campaign_id,campaign_name,channel,region,start_date,budget_usd,leads_generated,conversions,roi_percent,status
0,CMP-00001,Summer Sale,Social Media,West,2022-08-17,TBD,712.0,30.0,57.78,Inactive
1,CMP-00002,Summer Sale,Organic,West,2023-04-05,$925,3462.0,489.0,NaN,Completed
2,CMP-00003,Summer Sale,Email,North,2022-05-08,5664 USD,2962.0,71.0,194.99,Active
3,CMP-00004,Summer Sale,Ppc,East,2023-01-15,$14230,4990.0,746.0,40.65,Inactive
4,CMP-00005,Summer Sale,Email,North,2024-04-04,26790.0,2449.0,489.0,NaN,Completed
5,CMP-00006,Summer Sale,Organic,North,2024-02-04,38742.0,1133.0,773.0,256.94%,Completed
6,CMP-00007,Black Friday,Email,NaN,2023-06-26,36756,938.0,489.0,NaN,Completed
7,CMP-00008,Holiday Special,Organic,East,2023-06-04,TBD,2449.0,780.0,157.0,Active
8,CMP-00009,Summer Sale,Social Media,South,2024-06-18,16192 USD,2449.0,835.0,293.18%,Completed
9,CMP-00010,New Year Promo,Social Media,North,2024-06-12,14380.0,2553.0,489.0,125.81,Active
10,CMP-00011,Summer Sale,Email,North,2022-08-24,971,1875.0,489.0,11.97,Completed
11,CMP-00012,Summer Sale,Email,NaN,2022-09-06,$27177,2449.0,478.0,198.74,Active
12,CMP-00013,Black Friday,Email,West,2022-07-14,9686.00,3789.0,453.0,20.0,Active
13,CMP-00014,Back To School,Ppc,NaN,2023-05-13,14508,2449.0,489.0,78.43,Inactive
14,CMP-00015,Holiday Special,Email,North,2023-08-17,49519,4785.0,161.0,287.84%,Inactive
15,CMP-00016,Back To School,Organic,South,2023-07-08,38440 USD,671.0,578.0,88.07,Completed
16,CMP-00017,New Year Promo,Social Media,NaN,2022-11-20,1110 USD,819.0,489.0,31.06,Active
17,CMP-00018,Summer Sale,Organic,North,2023-09-19,44269.00,848.0,270.0,265.81%,Active
18,CMP-00019,Summer Sale,Email,North,2023-06-02,16957,2449.0,45.0,NaN,Completed
19,CMP-00020,Black Friday,Organic,North,2022-04-25,TBD,295.0,565.0,NaN,Active
20,CMP-00021,Back To School,Social Media,South,2024-03-09,41175.0,1331.0,489.0,NaN,Completed
21,CMP-00022,Black Friday,Organic,North,2024-05-29,NaN,2864.0,228.0,NaN,Inactive
22,CMP-00023,Summer Sale,Organic,North,2022-12-06,8059.00,2449.0,39.0,NaN,Completed
23,CMP-00024,Black Friday,Organic,East,2022-07-14,3408,4259.0,703.0,102.91,Completed
24,CMP-00025,Black Friday,Social Media,North,2022-11-13,21876.00,2449.0,489.0,200.0,Pending
25,CMP-00026,Summer Sale,Social Media,North,2022-08-04,38509,3809.0,218.0,136.69,Completed
26,CMP-00027,Summer Sale,Ppc,South,2024-04-18,44592.0,1207.0,486.0,NaN,Pending
27,CMP-00028,Black Friday,Email,NaN,2022-07-09,$43495,3482.0,489.0,5.57,Completed
28,CMP-00029,Summer Sale,Organic,East,2022-11-21,TBD,3495.0,456.0,NaN,Active
29,CMP-00030,Summer Sale,Email,West,2022-10-09,5577.0,2225.0,82.0,36.76%,Active
30,CMP-00031,Summer Sale,Organic,NaN,2023-03-02,NaN,4784.0,877.0,NaN,Active
31,CMP-00032,Black Friday,Organic,North,2024-03-30,NaN,2449.0,489.0,214.5%,Pending
32,CMP-00033,Black Friday,Email,East,2023-11-10,"$6,001",2449.0,489.0,NaN,Active
33,CMP-00034,Black Friday,Email,North,2024-02-07,$23435,329.0,204.0,NaN,Inactive
34,CMP-00035,Summer Sale,Social Media,South,2022-06-21,$11232,2449.0,489.0,112.96,Pending
35,CMP-00036,Holiday Special,Email,South,2024-03-26,23254,2449.0,489.0,NaN,Completed
36,CMP-00037,Summer Sale,Social Media,East,2024-04-07,30965 USD,2198.0,850.0,NaN,Pending
37,CMP-00038,Summer Sale,Email,NaN,2024-05-21,12417,2116.0,489.0,162.3%,Inactive
38,CMP-00039,Summer Sale,Organic,West,2023-12-09,NaN,141.0,414.0,NaN,Inactive
39,CMP-00040,Summer Sale,Ppc,South,2023-12-21,18254.0,2449.0,122.0,284.77%,Active
40,CMP-00041,Summer Sale,Organic,East,2022-10-17,13221,1469.0,546.0,75.0,Active
41,CMP-00042,Summer Sale,Social Media,North,2023-08-11,31262,2449.0,489.0,NaN,Inactive
42,CMP-00043,Summer Sale,Ppc,East,2024-04-10,$6082,4571.0,610.0,NaN,Completed
43,CMP-00044,Black Friday,Social Media,East,2023-09-28,$40452,2449.0,676.0,38.69,Completed
44,CMP-00045,Summer Sale,Email,North,2022-03-02,NaN,2449.0,806.0,NaN,Inactive
45,CMP-00046,New Year Promo,Social Media,East,2022-03-15,11373 USD,2449.0,489.0,NaN,Inactive
46,CMP-00047,Black Friday,Email,North,2023-03-19,$40064,1875.0,601.0,NaN,Pending
47,CMP-00048,New Year Promo,Email,North,2023-10-30,18729 USD,2449.0,992.0,NaN,Inactive
48,CMP-00049,Summer Sale,Social Media,NaN,2024-04-13,30307.00,2449.0,885.0,246.0,Completed
49,CMP-00050,Summer Sale,Ppc,East,2024-02-14,41486,1667.0,489.0,125.82,Active

In [23]:
# Convert region column into string
df['region'] = df['region'].astype(str)

# Remove extra spaces
df['region'] = df['region'].str.strip()

# Convert into proper format
df['region'] = df['region'].str.title()

# Replace invalid values with NaN
df['region'] = df['region'].replace(
    ['Nan', 'Unknown', ''],
    np.nan
)

# Fill missing values using mode
df['region'] = df['region'].fillna(
    df['region'].mode()[0]
)

# Check final output
print(df['region'].unique())

<StringArray>
['West', 'North', 'East', 'South']
Length: 4, dtype: str

In [24]:
# Convert budget column into string
df['budget_usd'] = df['budget_usd'].astype(str)

# Remove $, USD and commas
df['budget_usd'] = df['budget_usd'].str.replace('$', '', regex=False)
df['budget_usd'] = df['budget_usd'].str.replace('USD', '', regex=False)
df['budget_usd'] = df['budget_usd'].str.replace(',', '', regex=False)

# Remove extra spaces
df['budget_usd'] = df['budget_usd'].str.strip()

# Replace invalid values with NaN
df['budget_usd'] = df['budget_usd'].replace(
    ['TBD', 'Nan', ''],
    np.nan
)

# Convert into numeric datatype
df['budget_usd'] = pd.to_numeric(
    df['budget_usd'],
    errors='coerce'
)

# Fill missing values using median
df['budget_usd'] = df['budget_usd'].fillna(
    df['budget_usd'].median()
)

# Check output
print(df['budget_usd'].head())
print(df['budget_usd'].dtype)

0    25673.0
1      925.0
2     5664.0
3    14230.0
4    26790.0
Name: budget_usd, dtype: float64
float64

In [25]:
# Convert roi_percent column into string
df['roi_percent'] = df['roi_percent'].astype(str)

# Remove % sign
df['roi_percent'] = df['roi_percent'].str.replace(
    '%',
    '',
    regex=False
)

# Remove extra spaces
df['roi_percent'] = df['roi_percent'].str.strip()

# Replace invalid values with NaN
df['roi_percent'] = df['roi_percent'].replace(
    ['Nan', 'Unknown', ''],
    np.nan
)

# Convert into numeric datatype
df['roi_percent'] = pd.to_numeric(
    df['roi_percent'],
    errors='coerce'
)

# Fill missing values using median
df['roi_percent'] = df['roi_percent'].fillna(
    df['roi_percent'].median()
)

# Check output
print(df['roi_percent'].head())
print(df['roi_percent'].dtype)

0     57.78
1    137.84
2    194.99
3     40.65
4    137.84
Name: roi_percent, dtype: float64
float64

In [26]:
df.isnull().sum()

campaign_id        63
campaign_name       0
channel             0
region              0
start_date          0
budget_usd          0
leads_generated     0
conversions         0
roi_percent         0
status              0
dtype: int64

In [27]:
# Find missing campaign IDs
missing_mask = df['campaign_id'].isnull()

# Generate new unique IDs
df.loc[missing_mask, 'campaign_id'] = [
    f"CMP-{i:05d}" 
    for i in range(10001, 10001 + missing_mask.sum())
]

# Check again
print(df['campaign_id'].isnull().sum())

# Preview
print(df['campaign_id'].head(20))

0
0     CMP-00001
1     CMP-00002
2     CMP-00003
3     CMP-00004
4     CMP-00005
5     CMP-00006
6     CMP-00007
7     CMP-00008
8     CMP-00009
9     CMP-00010
10    CMP-00011
11    CMP-00012
12    CMP-00013
13    CMP-00014
14    CMP-00015
15    CMP-00016
16    CMP-00017
17    CMP-00018
18    CMP-00019
19    CMP-00020
Name: campaign_id, dtype: str

In [28]:
df.duplicated().sum()

np.int64(0)

In [29]:
df.isnull().sum()

campaign_id        0
campaign_name      0
channel            0
region             0
start_date         0
budget_usd         0
leads_generated    0
conversions        0
roi_percent        0
status             0
dtype: int64

In [30]:
df.describe()

,start_date,budget_usd,leads_generated,conversions,roi_percent
count,6000,6000.000000,6000.0000,6000.000000,6000.000000
mean,2023-04-03 09:14:38.400000,25458.097333,2449.5960,491.025833,138.471288
min,2022-01-01 00:00:00,-49660.000000,-4947.0000,0.000000,-287.970000
25%,2022-08-17 00:00:00,18588.750000,1862.0000,391.000000,101.000000
50%,2023-04-03 00:00:00,25673.000000,2449.0000,489.000000,137.840000
75%,2023-11-16 00:00:00,32075.500000,3046.2500,582.000000,175.265000
max,2024-12-06 00:00:00,49973.000000,5000.0000,1000.000000,300.000000
std,NaN,11973.194385,1221.5713,227.360744,75.435021

In [31]:
num_cols = ['budget_usd', 'leads_generated', 'conversions', 'roi_percent']

for col in num_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    before = len(df)
    df = df[(df[col] >= lower) & (df[col] <= upper)]
    print(f"{col}: removed {before - len(df)} outlier rows")

budget_usd: removed 12 outlier rows
leads_generated: removed 260 outlier rows
conversions: removed 779 outlier rows
roi_percent: removed 144 outlier rows

In [32]:
columns = ['budget_usd', 'leads_generated', 'conversions', 'roi_percent']

for col in columns:
    
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    df = df[
        (df[col] >= lower) &
        (df[col] <= upper)
     ]

print(df.shape)

(2582, 10)

In [33]:
print(df.dtypes)

campaign_id                   str
campaign_name                 str
channel                       str
region                        str
start_date         datetime64[us]
budget_usd                float64
leads_generated           float64
conversions               float64
roi_percent               float64
status                        str
dtype: object

In [34]:
df['channel'].unique()

<StringArray>
['Organic', 'Email', 'Social Media', 'Ppc']
Length: 4, dtype: str

In [35]:
df['region'].unique()

<StringArray>
['West', 'North', 'South', 'East']
Length: 4, dtype: str

In [36]:

df['campaign_name'].unique()

<StringArray>
[   'Summer  Sale',     'Summer Sale',    'Black Friday',  'New Year Promo',
  'Back To School', 'Holiday Special']
Length: 6, dtype: str

In [37]:
print(df['start_date'].head())
print(df['start_date'].dtype)

1    2023-04-05
4    2024-04-04
6    2023-06-26
9    2024-06-12
10   2022-08-24
Name: start_date, dtype: datetime64[us]
datetime64[us]

In [38]:
df.to_csv('marketing_campaign_cleaned.csv', index=False)

In [39]:
df.info()

<class 'pandas.DataFrame'>
Index: 2582 entries, 1 to 5998
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   campaign_id      2582 non-null   str
 1   campaign_name    2582 non-null   str
 2   channel          2582 non-null   str
 3   region           2582 non-null   str
 4   start_date       2582 non-null   datetime64[us]
 5   budget_usd       2582 non-null   float64
 6   leads_generated  2582 non-null   float64
 7   conversions      2582 non-null   float64
 8   roi_percent      2582 non-null   float64
 9   status           2582 non-null   str
dtypes: datetime64[us](1), float64(4), str(5)
memory usage: 221.9 KB

In [40]:
df.shape

(2582, 10)

In [52]:
df.to_csv('marketing_campaign_cleaned.csv', index=False)

In [53]:
pip install psycopg2-binary sqlalchemy

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.12-cp313-cp313-win_amd64.whl.metadata (5.1 kB)
Requirement already satisfied: sqlalchemy in .\miniconda3\Lib\site-packages (2.0.49)
Requirement already satisfied: greenlet>=1 in .\miniconda3\Lib\site-packages (from sqlalchemy) (3.4.0)
Requirement already satisfied: typing-extensions>=4.6.0 in .\miniconda3\Lib\site-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.12-cp313-cp313-win_amd64.whl (2.8 MB)
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   ------- -------------------------------- 0.5/2.8 MB 1.6 MB/s eta 0:00:02
   --------------- ------------------------ 1.0/2.8 MB 1.5 MB/s eta 0:00:02
   ---------------------- ----------------- 1.6/2.8 MB 1.7 MB/s eta 0:00:01
   -------------------------- ------------- 1.8/2.8 MB 1.7 MB/s eta 0:00:01
   ---------------------------------- ----- 2.4/2.8 MB 1.8 MB/s eta 0:00:01
   -------------------------------------- - 2.6/2.8 MB 1.8 MB/s eta 0:00:01
   ---------------------------------------- 2.8/2.8 MB 1.7 MB/s  0:00:01
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.12
Note: you may need to restart the kernel to use updated packages.

In [55]:
username = "postgres"
password = 1234
host = "localhost"
port = "5432"
database = "marketing_campaign"

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

df.to_sql(
    name='marketing_campaign',
    con=engine,
    if_exists='replace',
    index=False
)

582

In [56]:
print("Data exported successfully")

Data exported successfully